spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_oms?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8 # %2B
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 调整每个entity的id为自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000