server:
  port: 12010

spring:
  application:
    name: gulimall-search

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

#logging:
#  level:
#    com.finn.gulimall.search: debug
#    root: warn
#  pattern:
#    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"